CREATE DATABASE IF NOT EXISTS ci4 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
USE ci4;

CREATE USER IF NOT EXISTS 'ci4'@'localhost' IDENTIFIED BY 'ci4';
GRANT ALL PRIVILEGES ON ci4.* TO 'ci4'@'localhost';
FLUSH PRIVILEGES;

DROP TABLE IF EXISTS alumnos;

CREATE TABLE alumnos (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  codigo   VARCHAR(50)  NOT NULL,
  nombres  VARCHAR(100) NOT NULL,
  apellidos VARCHAR(100) NOT NULL,
  telefono VARCHAR(30)  NOT NULL,
  UNIQUE KEY uq_alumnos_codigo (codigo)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
